trigger:
- '*'

variables:
  webRepository: 'web'
  tag: '$(Build.BuildId)'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '3.1.300'
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:

    - task: Docker@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Salma-Release'
        azureContainerRegistry: '{"loginServer":"tailspinspacegame27900.azurecr.io", "id" : "/subscriptions/5ccadedb-8ce8-43da-8d17-f91b671c9110/resourceGroups/tailspin-space-game-rg/providers/Microsoft.ContainerRegistry/registries/tailspinspacegame27900"}'
        action: 'Build an image'
        dockerFile: '$(Build.SourcesDirectory)/DOCKER'
        buildArguments: 'baseimage=tailspinspacegame27900.azurecr.io/web:latest'
        imageName: 'tailspinspacegame27900:$(Build.BuildId)'
        additionalImageTags: '$(tag)'
        includeLatestTag: true
        
    - task: Docker@0
      displayName: 'Push an image'
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Salma-Release'
        azureContainerRegistry: '{"loginServer":"tailspinspacegame27900.azurecr.io", "id" : "/subscriptions/5ccadedb-8ce8-43da-8d17-f91b671c9110/resourceGroups/tailspin-space-game-rg/providers/Microsoft.ContainerRegistry/registries/tailspinspacegame27900"}'
        action: 'Push an image'
        imageName: 'tailspinspacegame27900:$(Build.BuildId)'

- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      vmImage: 'ubuntu-18.04'
    variables:
    - group: Release
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Salma-Release'
        appName: 'tailspin-space-game-web-27900'
        containers: 'tailspinspacegame27900.azurecr.io/web:latest'